name: "My Custom Action"
description: "This is my own action that prints a message"
inputs:
  message:
    description: "Message to print"
    required: true
    default: "Hello from my action!"
outputs:
  outputMessage:
    description: "Output message after action runs"
runs:
  using: "node16"
  main: "index.js"