name: "Pylint Badge Composite"
description: "Run Pylint and calculate score"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      shell: bash

    - name: Run Pylint and calculate score
      id: pylint
      run: |
        SCORE=$(pylint . --exit-zero | tail -n 1 | grep -o "[0-9]\\+\\(\\.[0-9]\\+\\)?")
        echo "score=$SCORE" >> $GITHUB_OUTPUT
      shell: bash