name: "Pylint Badge Docker Action"
description: "Generates a pylint badge and publishes to gh-pages"
inputs:
  path:
    description: "Path to lint"
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
