jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devs-des1re/pylint-badge@v1
        id: pylint
      - name: Push badge to gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B gh-pages
          cp -r badges/* .
          git add .
          git commit -m "Update pylint badge" || echo "No changes"
          git push -u origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
