name: My Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run my custom action
        uses: ./action
        with:
          message: "Hello, GitHub Actions!"
