name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  custom-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd action
          npm install

      - name: Run My Custom Action
        uses: ./action
        with:
          message: "Hello from my action!"